<?php
// filepath: c:\xampp\htdocs\alpha_airconex\script\insert_products.php
// Database configuration
$servername = "localhost";
$username = "root";
$password = "";
$dbname = "alpha_airconex";

try {
    // Create connection
    $pdo = new PDO("mysql:host=$servername;dbname=$dbname", $username, $password);
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    
    // New PANASONIC Products array
    $newProducts = [
        ['PANASONIC', 'CS-PU9WKQ-CU-PU9WKQ', '1.0HP PANASONIC WALL MOUNTED - STANDARD INVERTER (CS-PU9WKQ / CU-PU9WKQ)', '1.0HP', 'WALL MOUNTED', 'CS-PU9WKQ', 'CU-PU9WKQ', 'Standard Inverter'],
        ['PANASONIC', 'CS-PU12WKQ-CU-PU12WKQ', '1.5HP PANASONIC WALL MOUNTED - STANDARD INVERTER (CS-PU12WKQ / CU-PU12WKQ)', '1.5HP', 'WALL MOUNTED', 'CS-PU12WKQ', 'CU-PU12WKQ', 'Standard Inverter'],
        ['PANASONIC', 'CS-PU12VKQ-CU-PU12VKQ', '1.5HP PANASONIC WALL MOUNTED - STANDARD INVERTER (CS-PU12VKQ / CU-PU12VKQ)', '1.5HP', 'WALL MOUNTED', 'CS-PU12VKQ', 'CU-PU12VKQ', 'Standard Inverter'],
        ['PANASONIC', 'CS-PU18WKQ-CU-PU18WKQ', '2.0HP PANASONIC WALL MOUNTED - STANDARD INVERTER (CS-PU18WKQ / CU-PU18WKQ)', '2.0HP', 'WALL MOUNTED', 'CS-PU18WKQ', 'CU-PU18WKQ', 'Standard Inverter'],
        ['PANASONIC', 'CS-PU24XKQ-CU-PU24XKQ', '2.5HP PANASONIC WALL MOUNTED - STANDARD INVERTER (CS-PU24XKQ / CU-PU24XKQ)', '2.5HP', 'WALL MOUNTED', 'CS-PU24XKQ', 'CU-PU24XKQ', 'Standard Inverter'],
        ['PANASONIC', 'CS-PU9AKQ-CU-PU9AKQ', '1.0HP PANASONIC WALL MOUNTED - STANDARD INVERTER (CS-PU9AKQ / CU-PU9AKQ)', '1.0HP', 'WALL MOUNTED', 'CS-PU9AKQ', 'CU-PU9AKQ', 'Standard Inverter'],
        ['PANASONIC', 'CS-PU12AKQ-CU-PU12AKQ', '1.5HP PANASONIC WALL MOUNTED - STANDARD INVERTER (CS-PU12AKQ / CU-PU12AKQ)', '1.5HP', 'WALL MOUNTED', 'CS-PU12AKQ', 'CU-PU12AKQ', 'Standard Inverter'],
        ['PANASONIC', 'CS-PU9AKQ(PS)-CU-RU9AKQ(PS)', '1.0HP PANASONIC WALL MOUNTED - STANDARD INVERTER (CS-PU9AKQ(PS) / CU-RU9AKQ(PS))', '1.0HP', 'WALL MOUNTED', 'CS-PU9AKQ(PS)', 'CU-RU9AKQ(PS)', 'Standard Inverter'],
        ['PANASONIC', 'CS-PU18AKQ-CU-RU18AKQ(PS)', '2.0HP PANASONIC WALL MOUNTED - STANDARD INVERTER (CS-PU18AKQ / CU-RU18AKQ(PS))', '2.0HP', 'WALL MOUNTED', 'CS-PU18AKQ', 'CU-RU18AKQ(PS)', 'Standard Inverter'],
        ['PANASONIC', 'CS-PU24AKQ-CU-PU24AKQ', '2.5HP PANASONIC WALL MOUNTED - STANDARD INVERTER (CS-PU24AKQ / CU-PU24AKQ)', '2.5HP', 'WALL MOUNTED', 'CS-PU24AKQ', 'CU-PU24AKQ', 'Standard Inverter'],
        ['PANASONIC', 'CS-PU24AKQ(S)-CU-RU24AKQ(S)', '2.5HP PANASONIC WALL MOUNTED - STANDARD INVERTER (CS-PU24AKQ(S) / CU-RU24AKQ(S))', '2.5HP', 'WALL MOUNTED', 'CS-PU24AKQ(S)', 'CU-RU24AKQ(S)', 'Standard Inverter'],
        ['PANASONIC', 'CS-PU30AKQ-CU-XU30AKQ(S)', '3.0HP PANASONIC WALL MOUNTED - STANDARD INVERTER (CS-PU30AKQ / CU-XU30AKQ(S))', '3.0HP', 'WALL MOUNTED', 'CS-PU30AKQ', 'CU-XU30AKQ(S)', 'Standard Inverter'],
        ['PANASONIC', 'CS-XU9AKQ-CU-XU9AKQ', '1.0HP PANASONIC WALL MOUNTED - PREMIUM INVERTER (CS-XU9AKQ / CU-XU9AKQ)', '1.0HP', 'WALL MOUNTED', 'CS-XU9AKQ', 'CU-XU9AKQ', 'Premium Inverter'],
        ['PANASONIC', 'CS-XU12AKQ-CU-XU12AKQ', '1.5HP PANASONIC WALL MOUNTED - PREMIUM INVERTER (CS-XU12AKQ / CU-XU12AKQ)', '1.5HP', 'WALL MOUNTED', 'CS-XU12AKQ', 'CU-XU12AKQ', 'Premium Inverter'],
        ['PANASONIC', 'CS-XU18AKQ-CU-XU18AKQ', '2.0HP PANASONIC WALL MOUNTED - PREMIUM INVERTER (CS-XU18AKQ / CU-XU18AKQ)', '2.0HP', 'WALL MOUNTED', 'CS-XU18AKQ', 'CU-XU18AKQ', 'Premium Inverter'],
        ['PANASONIC', 'CS-XU24AKQ-CU-XU24AKQ', '2.5HP PANASONIC WALL MOUNTED - PREMIUM INVERTER (CS-XU24AKQ / CU-XU24AKQ)', '2.5HP', 'WALL MOUNTED', 'CS-XU24AKQ', 'CU-XU24AKQ', 'Premium Inverter'],
        ['PANASONIC', 'CS-XU30AKQ-CU-XU30AKQ', '3.0HP PANASONIC WALL MOUNTED - PREMIUM INVERTER (CS-XU30AKQ / CU-XU30AKQ)', '3.0HP', 'WALL MOUNTED', 'CS-XU30AKQ', 'CU-XU30AKQ', 'Premium Inverter'],
        ['PANASONIC', 'CS-PU36WKQ-CU-PU36WKQ', '4.0HP PANASONIC WALL MOUNTED - STANDARD INVERTER (CS-PU36WKQ / CU-PU36WKQ)', '4.0HP', 'WALL MOUNTED', 'CS-PU36WKQ', 'CU-PU36WKQ', 'Standard Inverter'],
        ['PANASONIC', 'CS-XPU9WKQ-CU-XPU9WKQ', '1.0HP PANASONIC WALL MOUNTED - DELUXE INVERTER (CS-XPU9WKQ / CU-XPU9WKQ)', '1.0HP', 'WALL MOUNTED', 'CS-XPU9WKQ', 'CU-XPU9WKQ', 'Deluxe Inverter'],
        ['PANASONIC', 'CS-XPU12WKQ-CU-XPU12WKQ', '1.5HP PANASONIC WALL MOUNTED - DELUXE INVERTER (CS-XPU12WKQ / CU-XPU12WKQ)', '1.5HP', 'WALL MOUNTED', 'CS-XPU12WKQ', 'CU-XPU12WKQ', 'Deluxe Inverter'],
        ['PANASONIC', 'CS-XPU18WKQ-CU-XPU18WKQ', '2.0HP PANASONIC WALL MOUNTED - DELUXE INVERTER (CS-XPU18WKQ / CU-XPU18WKQ)', '2.0HP', 'WALL MOUNTED', 'CS-XPU18WKQ', 'CU-XPU18WKQ', 'Deluxe Inverter'],
        ['PANASONIC', 'CS-XPU24XKQ-CU-XPU24XKQ', '2.5HP PANASONIC WALL MOUNTED - DELUXE INVERTER (CS-XPU24XKQ / CU-XPU24XKQ)', '2.5HP', 'WALL MOUNTED', 'CS-XPU24XKQ', 'CU-XPU24XKQ', 'Deluxe Inverter'],
        ['PANASONIC', 'CS-XU9XKQ-CU-XU9XKQ', '1.0HP PANASONIC WALL MOUNTED - PREMIUM INVERTER (CS-XU9XKQ / CU-XU9XKQ)', '1.0HP', 'WALL MOUNTED', 'CS-XU9XKQ', 'CU-XU9XKQ', 'Premium Inverter'],
        ['PANASONIC', 'CS-XU12XKQ-CU-XU12XKQ', '1.5HP PANASONIC WALL MOUNTED - PREMIUM INVERTER (CS-XU12XKQ / CU-XU12XKQ)', '1.5HP', 'WALL MOUNTED', 'CS-XU12XKQ', 'CU-XU12XKQ', 'Premium Inverter'],
        ['PANASONIC', 'CS-XU18XKQ-CU-XU18XKQ', '2.0HP PANASONIC WALL MOUNTED - PREMIUM INVERTER (CS-XU18XKQ / CU-XU18XKQ)', '2.0HP', 'WALL MOUNTED', 'CS-XU18XKQ', 'CU-XU18XKQ', 'Premium Inverter'],
        ['PANASONIC', 'CS-XU24XKQ-CU-XU24XKQ', '2.5HP PANASONIC WALL MOUNTED - PREMIUM INVERTER (CS-XU24XKQ / CU-XU24XKQ)', '2.5HP', 'WALL MOUNTED', 'CS-XU24XKQ', 'CU-XU24XKQ', 'Premium Inverter'],
        ['PANASONIC', 'CS-XU30VKQ-CU-XU30VKQ', '3.0HP PANASONIC WALL MOUNTED - PREMIUM INVERTER (CS-XU30VKQ / CU-XU30VKQ)', '3.0HP', 'WALL MOUNTED', 'CS-XU30VKQ', 'CU-XU30VKQ', 'Premium Inverter'],
        ['PANASONIC', 'CS-PN9XKQ-CU-PN9XKQ', '1.0HP PANASONIC WALL MOUNTED - NON-INVERTER (CS-PN9XKQ / CU-PN9XKQ)', '1.0HP', 'WALL MOUNTED', 'CS-PN9XKQ', 'CU-PN9XKQ', 'Non-Inverter'],
        ['PANASONIC', 'CS-PN12XKQ-CU-PN12XKQ', '1.5HP PANASONIC WALL MOUNTED - NON-INVERTER (CS-PN12XKQ / CU-PN12XKQ)', '1.5HP', 'WALL MOUNTED', 'CS-PN12XKQ', 'CU-PN12XKQ', 'Non-Inverter'],
        ['PANASONIC', 'CS-PN18XKQ-CU-PN18XKQ', '2.0HP PANASONIC WALL MOUNTED - NON-INVERTER (CS-PN18XKQ / CU-PN18XKQ)', '2.0HP', 'WALL MOUNTED', 'CS-PN18XKQ', 'CU-PN18XKQ', 'Non-Inverter'],
        ['PANASONIC', 'CS-PN24XKQ-CU-PN24XKQ', '2.5HP PANASONIC WALL MOUNTED - NON-INVERTER (CS-PN24XKQ / CU-PN24XKQ)', '2.5HP', 'WALL MOUNTED', 'CS-PN24XKQ', 'CU-PN24XKQ', 'Non-Inverter'],
        ['PANASONIC', 'S-24PB3Q6-U-24PB3Q6', '3.0HP PANASONIC FLOOR STANDING - INVERTER (S-24PB3Q6 / U-24PB3Q6)', '3.0HP', 'FLOOR STANDING', 'S-24PB3Q6', 'U-24PB3Q6', 'Inverter'],
        ['PANASONIC', 'S-34PB3Q6-U-34PB3Q6', '4.0HP PANASONIC FLOOR STANDING - INVERTER (S-34PB3Q6 / U-34PB3Q6)', '4.0HP', 'FLOOR STANDING', 'S-34PB3Q6', 'U-34PB3Q6', 'Inverter'],
        ['PANASONIC', 'S-38PB2Q6-U-38PS2Q6', '4.5HP PANASONIC FLOOR STANDING - INVERTER (S-38PB2Q6 / U-38PS2Q6)', '4.5HP', 'FLOOR STANDING', 'S-38PB2Q6', 'U-38PS2Q6', 'Inverter'],
        ['PANASONIC', 'S-43PB3Q6-U-43PSB3Q6', '5.0HP PANASONIC FLOOR STANDING - INVERTER (S-43PB3Q6 / U-43PSB3Q6)', '5.0HP', 'FLOOR STANDING', 'S-43PB3Q6', 'U-43PSB3Q6', 'Inverter'],
        ['PANASONIC', 'S-48PB3Q6-U-48PB3Q6', '6.0HP PANASONIC FLOOR STANDING - INVERTER (S-48PB3Q6 / U-48PB3Q6)', '6.0HP', 'FLOOR STANDING', 'S-48PB3Q6', 'U-48PB3Q6', 'Inverter'],
        ['PANASONIC', 'S-18PT3Q6-U-18PT3Q6', '2.0HP PANASONIC CEILING MOUNTED - STANDARD INVERTER (S-18PT3Q6 / U-18PT3Q6)', '2.0HP', 'CEILING MOUNTED', 'S-18PT3Q6', 'U-18PT3Q6', 'Standard Inverter'],
        ['PANASONIC', 'S-21PT3Q6-U-21PT3Q6', '2.5HP PANASONIC CEILING MOUNTED - STANDARD INVERTER (S-21PT3Q6 / U-21PT3Q6)', '2.5HP', 'CEILING MOUNTED', 'S-21PT3Q6', 'U-21PT3Q6', 'Standard Inverter'],
        ['PANASONIC', 'S-24PT3Q6-U-24PT3Q6', '3.0HP PANASONIC CEILING MOUNTED - STANDARD INVERTER (S-24PT3Q6 / U-24PT3Q6)', '3.0HP', 'CEILING MOUNTED', 'S-24PT3Q6', 'U-24PT3Q6', 'Standard Inverter'],
        ['PANASONIC', 'S-24PT3Q6-U-24PR1Q6', '3.0HP PANASONIC CEILING MOUNTED - STANDARD INVERTER (S-24PT3Q6 / U-24PR1Q6)', '3.0HP', 'CEILING MOUNTED', 'S-24PT3Q6', 'U-24PR1Q6', 'Standard Inverter'],
        ['PANASONIC', 'S-30PT3Q6-U-30PT3Q6', '3.5HP PANASONIC CEILING MOUNTED - STANDARD INVERTER (S-30PT3Q6 / U-30PT3Q6)', '3.5HP', 'CEILING MOUNTED', 'S-30PT3Q6', 'U-30PT3Q6', 'Standard Inverter'],
        ['PANASONIC', 'S-34PT3Q-U-34PT3Q', '4.0HP PANASONIC CEILING MOUNTED - STANDARD INVERTER (S-34PT3Q / U-34PT3Q)', '4.0HP', 'CEILING MOUNTED', 'S-34PT3Q', 'U-34PT3Q', 'Standard Inverter'],
        ['PANASONIC', 'S-43PT3Q6-U-43PT3Q6', '5.0HP PANASONIC CEILING MOUNTED - STANDARD INVERTER (S-43PT3Q6 / U-43PT3Q6)', '5.0HP', 'CEILING MOUNTED', 'S-43PT3Q6', 'U-43PT3Q6', 'Standard Inverter'],
        ['PANASONIC', 'S-48PT3Q6-U-48PT3Q6', '6.0HP PANASONIC CEILING MOUNTED - STANDARD INVERTER (S-48PT3Q6 / U-48PT3Q6)', '6.0HP', 'CEILING MOUNTED', 'S-48PT3Q6', 'U-48PT3Q6', 'Standard Inverter'],
        ['PANASONIC', 'S-43PT3Q9-U-43PT3Q9', '5.0HP PANASONIC CEILING MOUNTED - INVERTER - 3-PHASE (S-43PT3Q9 / U-43PT3Q9)', '5.0HP', 'CEILING MOUNTED', 'S-43PT3Q9', 'U-43PT3Q9', 'Inverter - 3-Phase'],
        ['PANASONIC', 'S-48PT3Q9-U-48PT3Q9', '6.0HP PANASONIC CEILING MOUNTED - INVERTER - 3-PHASE (S-48PT3Q9 / U-48PT3Q9)', '6.0HP', 'CEILING MOUNTED', 'S-48PT3Q9', 'U-48PT3Q9', 'Inverter - 3-Phase'],
        ['PANASONIC', 'S-18PT3QA6-U-18PT3QA6', '2.0HP PANASONIC CEILING MOUNTED - DELUXE INVERTER (S-18PT3QA6 / U-18PT3QA6)', '2.0HP', 'CEILING MOUNTED', 'S-18PT3QA6', 'U-18PT3QA6', 'Deluxe Inverter'],
        ['PANASONIC', 'S-21PT3QA6-U-21PT3QA6', '2.5HP PANASONIC CEILING MOUNTED - DELUXE INVERTER (S-21PT3QA6 / U-21PT3QA6)', '2.5HP', 'CEILING MOUNTED', 'S-21PT3QA6', 'U-21PT3QA6', 'Deluxe Inverter'],
        ['PANASONIC', 'S-24PT3QA6-U-24PT3QA6', '3.0HP PANASONIC CEILING MOUNTED - DELUXE INVERTER (S-24PT3QA6 / U-24PT3QA6)', '3.0HP', 'CEILING MOUNTED', 'S-24PT3QA6', 'U-24PT3QA6', 'Deluxe Inverter'],
        ['PANASONIC', 'S-30PT3QA6-U-30PT3QA6', '3.5HP PANASONIC CEILING MOUNTED - DELUXE INVERTER (S-30PT3QA6 / U-30PT3QA6)', '3.5HP', 'CEILING MOUNTED', 'S-30PT3QA6', 'U-30PT3QA6', 'Deluxe Inverter'],
        ['PANASONIC', 'S-43PT3QA6-U-43PT3QA6', '5.0HP PANASONIC CEILING MOUNTED - DELUXE INVERTER (S-43PT3QA6 / U-43PT3QA6)', '5.0HP', 'CEILING MOUNTED', 'S-43PT3QA6', 'U-43PT3QA6', 'Deluxe Inverter'],
        ['PANASONIC', 'S-48PT3QA6-U-48PT3QA6', '6.0HP PANASONIC CEILING MOUNTED - DELUXE INVERTER (S-48PT3QA6 / U-48PT3QA6)', '6.0HP', 'CEILING MOUNTED', 'S-48PT3QA6', 'U-48PT3QA6', 'Deluxe Inverter'],
        ['PANASONIC', 'S-43PT3QA9-U-43PT3QA9', '5.0HP PANASONIC CEILING MOUNTED - DELUXE INVERTER - 3-PHASE (S-43PT3QA9 / U-43PT3QA9)', '5.0HP', 'CEILING MOUNTED', 'S-43PT3QA9', 'U-43PT3QA9', 'Deluxe Inverter - 3-Phase'],
        ['PANASONIC', 'S-48PT3QA9-U-48PT3QA9', '6.0HP PANASONIC CEILING MOUNTED - DELUXE INVERTER - 3-PHASE (S-48PT3QA9 / U-48PT3QA9)', '6.0HP', 'CEILING MOUNTED', 'S-48PT3QA9', 'U-48PT3QA9', 'Deluxe Inverter - 3-Phase'],
        ['PANASONIC', 'S-34PT2Q6-U-34PS2Q6', '4.0HP PANASONIC CEILING MOUNTED - INVERTER (S-34PT2Q6 / U-34PS2Q6)', '4.0HP', 'CEILING MOUNTED', 'S-34PT2Q6', 'U-34PS2Q6', 'Inverter'],
        ['PANASONIC', 'S-18PF3Q6-U-18PF3Q6', '2.0HP PANASONIC CEILING CONCEALED - INVERTER (S-18PF3Q6 / U-18PF3Q6)', '2.0HP', 'CEILING CONCEALED', 'S-18PF3Q6', 'U-18PF3Q6', 'Inverter'],
        ['PANASONIC', 'S-21PF3Q6-U-21PF3Q6', '2.5HP PANASONIC CEILING CONCEALED - INVERTER (S-21PF3Q6 / U-21PF3Q6)', '2.5HP', 'CEILING CONCEALED', 'S-21PF3Q6', 'U-21PF3Q6', 'Inverter'],
        ['PANASONIC', 'S-24PF3Q6-U-24PF3Q6', '3.0HP PANASONIC CEILING CONCEALED - INVERTER (S-24PF3Q6 / U-24PF3Q6)', '3.0HP', 'CEILING CONCEALED', 'S-24PF3Q6', 'U-24PF3Q6', 'Inverter'],
        ['PANASONIC', 'S-30PF3Q6-U-30PF3Q6', '3.5HP PANASONIC CEILING CONCEALED - INVERTER (S-30PF3Q6 / U-30PF3Q6)', '3.5HP', 'CEILING CONCEALED', 'S-30PF3Q6', 'U-30PF3Q6', 'Inverter'],
        ['PANASONIC', 'S-34PF3Q6-U-34PF3Q6', '4.0HP PANASONIC CEILING CONCEALED - INVERTER (S-34PF3Q6 / U-34PF3Q6)', '4.0HP', 'CEILING CONCEALED', 'S-34PF3Q6', 'U-34PF3Q6', 'Inverter'],
        ['PANASONIC', 'S-43PF3Q6-U-43PF3Q6', '5.0HP PANASONIC CEILING CONCEALED - INVERTER (S-43PF3Q6 / U-43PF3Q6)', '5.0HP', 'CEILING CONCEALED', 'S-43PF3Q6', 'U-43PF3Q6', 'Inverter'],
        ['PANASONIC', 'S-48PF3Q6-U-48PF3Q6', '6.0HP PANASONIC CEILING CONCEALED - INVERTER (S-48PF3Q6 / U-48PF3Q6)', '6.0HP', 'CEILING CONCEALED', 'S-48PF3Q6', 'U-48PF3Q6', 'Inverter'],
        ['PANASONIC', 'S-43PF3Q9-U-43PF3Q6', '5.0HP PANASONIC CEILING CONCEALED - INVERTER - 3-PHASE (S-43PF3Q9 / U-43PF3Q6)', '5.0HP', 'CEILING CONCEALED', 'S-43PF3Q9', 'U-43PF3Q6', 'Inverter - 3-Phase'],
        ['PANASONIC', 'S-48PF3Q9-U-48PF3Q6', '6.0HP PANASONIC CEILING CONCEALED - INVERTER - 3-PHASE (S-48PF3Q9 / U-48PF3Q6)', '6.0HP', 'CEILING CONCEALED', 'S-48PF3Q9', 'U-48PF3Q6', 'Inverter - 3-Phase'],
        ['PANASONIC', 'S-18PF3QA6-U-18PF3QA6', '2.0HP PANASONIC CEILING CONCEALED - INVERTER (S-18PF3QA6 / U-18PF3QA6)', '2.0HP', 'CEILING CONCEALED', 'S-18PF3QA6', 'U-18PF3QA6', 'Inverter'],
        ['PANASONIC', 'S-21PF3QA6-U-21PF3QA6', '2.5HP PANASONIC CEILING CONCEALED - INVERTER (S-21PF3QA6 / U-21PF3QA6)', '2.5HP', 'CEILING CONCEALED', 'S-21PF3QA6', 'U-21PF3QA6', 'Inverter'],
        ['PANASONIC', 'S-24PF3QA6-U-24PF3QA6', '3.0HP PANASONIC CEILING CONCEALED - INVERTER (S-24PF3QA6 / U-24PF3QA6)', '3.0HP', 'CEILING CONCEALED', 'S-24PF3QA6', 'U-24PF3QA6', 'Inverter'],
        ['PANASONIC', 'S-30PF3QA6-U-30PF3QA6', '3.5HP PANASONIC CEILING CONCEALED - INVERTER (S-30PF3QA6 / U-30PF3QA6)', '3.5HP', 'CEILING CONCEALED', 'S-30PF3QA6', 'U-30PF3QA6', 'Inverter'],
        ['PANASONIC', 'S-34PF3QA6-U-34PF3QA6', '4.0HP PANASONIC CEILING CONCEALED - INVERTER (S-34PF3QA6 / U-34PF3QA6)', '4.0HP', 'CEILING CONCEALED', 'S-34PF3QA6', 'U-34PF3QA6', 'Inverter'],
        ['PANASONIC', 'S-43PF3QA6-U-43PF3QA6', '5.0HP PANASONIC CEILING CONCEALED - INVERTER (S-43PF3QA6 / U-43PF3QA6)', '5.0HP', 'CEILING CONCEALED', 'S-43PF3QA6', 'U-43PF3QA6', 'Inverter'],
        ['PANASONIC', 'S-48PF3QA6-U-48PF3QA6', '6.0HP PANASONIC CEILING CONCEALED - INVERTER (S-48PF3QA6 / U-48PF3QA6)', '6.0HP', 'CEILING CONCEALED', 'S-48PF3QA6', 'U-48PF3QA6', 'Inverter'],
        ['PANASONIC', 'S-43PF3QA9-U-43PF3QA9', '5.0HP PANASONIC CEILING CONCEALED - INVERTER (S-43PF3QA9 / U-43PF3QA9)', '5.0HP', 'CEILING CONCEALED', 'S-43PF3QA9', 'U-43PF3QA9', 'Inverter'],
        ['PANASONIC', 'S-48PF3QA9-U-48PF3QA9', '6.0HP PANASONIC CEILING CONCEALED - INVERTER (S-48PF3QA9 / U-48PF3QA9)', '6.0HP', 'CEILING CONCEALED', 'S-48PF3QA9', 'U-48PF3QA9', 'Inverter'],
        ['PANASONIC', 'S-18PU3QA6-U-18PU3QA6', '2.0HP PANASONIC CEILING CASSETTE - STANDARD INVERTER (S-18PU3QA6 / U-18PU3QA6)', '2.0HP', 'CEILING CASSETTE', 'S-18PU3QA6', 'U-18PU3QA6', 'Standard Inverter'],
        ['PANASONIC', 'S-21PU3QA6-U-21PU3QA6', '2.5HP PANASONIC CEILING CASSETTE - STANDARD INVERTER (S-21PU3QA6 / U-21PU3QA6)', '2.5HP', 'CEILING CASSETTE', 'S-21PU3QA6', 'U-21PU3QA6', 'Standard Inverter'],
        ['PANASONIC', 'S-24PU3QA6-U-24PU3QA6', '3.0HP PANASONIC CEILING CASSETTE - STANDARD INVERTER (S-24PU3QA6 / U-24PU3QA6)', '3.0HP', 'CEILING CASSETTE', 'S-24PU3QA6', 'U-24PU3QA6', 'Standard Inverter'],
        ['PANASONIC', 'S-30PU3QA6-U-30PU3QA6', '3.5HP PANASONIC CEILING CASSETTE - STANDARD INVERTER (S-30PU3QA6 / U-30PU3QA6)', '3.5HP', 'CEILING CASSETTE', 'S-30PU3QA6', 'U-30PU3QA6', 'Standard Inverter'],
        ['PANASONIC', 'S-34PU3QA6-U-34PU3QA6', '4.0HP PANASONIC CEILING CASSETTE - STANDARD INVERTER (S-34PU3QA6 / U-34PU3QA6)', '4.0HP', 'CEILING CASSETTE', 'S-34PU3QA6', 'U-34PU3QA6', 'Standard Inverter'],
        ['PANASONIC', 'S-43PU3QA6-U-43PU3QA6', '5.0HP PANASONIC CEILING CASSETTE - STANDARD INVERTER (S-43PU3QA6 / U-43PU3QA6)', '5.0HP', 'CEILING CASSETTE', 'S-43PU3QA6', 'U-43PU3QA6', 'Standard Inverter'],
        ['PANASONIC', 'S-43PU3Q6-U-43PR1Q6', '5.0HP PANASONIC CEILING CASSETTE - STANDARD INVERTER (S-43PU3Q6 / U-43PR1Q6)', '5.0HP', 'CEILING CASSETTE', 'S-43PU3Q6', 'U-43PR1Q6', 'Standard Inverter'],
        ['PANASONIC', 'S-48PU3QA6-U-48PU3QA6', '6.0HP PANASONIC CEILING CASSETTE - STANDARD INVERTER (S-48PU3QA6 / U-48PU3QA6)', '6.0HP', 'CEILING CASSETTE', 'S-48PU3QA6', 'U-48PU3QA6', 'Standard Inverter'],
        ['PANASONIC', 'S-43PU3QA9-U-43PU3QA9', '5.0HP PANASONIC CEILING CASSETTE - STANDARD INVERTER - 3-PHASE (S-43PU3QA9 / U-43PU3QA9)', '5.0HP', 'CEILING CASSETTE', 'S-43PU3QA9', 'U-43PU3QA9', 'Standard Inverter - 3-Phase'],
        ['PANASONIC', 'S-48PU3QA9-U-48PU3QA9', '6.0HP PANASONIC CEILING CASSETTE - STANDARD INVERTER - 3-PHASE (S-48PU3QA9 / U-48PU3QA9)', '6.0HP', 'CEILING CASSETTE', 'S-48PU3QA9', 'U-48PU3QA9', 'Standard Inverter - 3-Phase'],
        ['PANASONIC', 'S-24PU2Q6-U-24PS2Q6', '3.0HP PANASONIC CEILING CASSETTE - NANO-EX (S-24PU2Q6 / U-24PS2Q6)', '3.0HP', 'CEILING CASSETTE', 'S-24PU2Q6', 'U-24PS2Q6', 'Nano-Ex'],
        ['PANASONIC', 'CZ-KPU3H-', '2.5HP PANASONIC CEILING CASSETTE - INVERTER (CZ-KPU3H)', '2.5HP', 'CEILING CASSETTE', '', 'CZ-KPU3H', 'Inverter'],
        ['PANASONIC', 'S-34PU2Q6-U-34PU2Q6', '3.0HP PANASONIC CEILING CASSETTE - INVERTER (S-34PU2Q6 / U-34PU2Q6)', '3.0HP', 'CEILING CASSETTE', 'S-34PU2Q6', 'U-34PU2Q6', 'Inverter'],
        ['PANASONIC', 'CS-MPU12YKZ-', '1.5HP PANASONIC WALL MOUNTED MULTI-SPLIT - IDU (CS-MPU12YKZ)', '1.5HP', 'WALL MOUNTED MULTI-SPLIT', 'CS-MPU12YKZ', '', 'IDU'],
        ['PANASONIC', 'CS-MPU18YKZ-', '2.0HP PANASONIC WALL MOUNTED MULTI-SPLIT - RAC MULTI SPLIT (CS-MPU18YKZ)', '2.0HP', 'WALL MOUNTED MULTI-SPLIT', 'CS-MPU18YKZ', '', 'RAC MULTI SPLIT'],
        ['PANASONIC', 'CS-MPU09YKZ-', '1.0HP PANASONIC WALL MOUNTED MULTI-SPLIT - IDU (CS-MPU09YKZ)', '1.0HP', 'WALL MOUNTED MULTI-SPLIT', 'CS-MPU09YKZ', '', 'IDU'],
        ['PANASONIC', 'CS-MXPU9YKZ-', '1.0HP PANASONIC WALL MOUNTED MULTI-SPLIT - IDU (CS-MXPU9YKZ)', '1.0HP', 'WALL MOUNTED MULTI-SPLIT', 'CS-MXPU9YKZ', '', 'IDU'],
        ['PANASONIC', 'FY-10ELN-', '1.2MTR PANASONIC AIR CURTAIN (FY-10ELN)', '1.2MTR', 'AIR CURTAIN', 'FY-10ELN', '', ''],
        ['PANASONIC', 'FY-14ESN-', '4.0MTR PANASONIC AIR CURTAIN (FY-14ESN)', '4.0MTR', 'AIR CURTAIN', 'FY-14ESN', '', ''],
        ['PANASONIC', 'CU-4U34YBZ-', '3.8HP PANASONIC RAC MULTI SPLIT - 3.8 HP MULTI-SPLIT TYPE OUTDOOR UNIT, R32 REFRIGERANT (CU-4U34YBZ)', '3.8HP', 'RAC MULTI SPLIT', '', 'CU-4U34YBZ', '3.8 HP Multi-Split Type Outdoor Unit, R32 Refrigerant'],
        ['PANASONIC', 'CS-MPU9YKZ-', '1.0HP PANASONIC RAC MULTI SPLIT - 1.0HP MULTI-SPLIT TYPE INDOOR UNIT STANDARD (CS-MPU9YKZ)', '1.0HP', 'RAC MULTI SPLIT', 'CS-MPU9YKZ', '', '1.0HP Multi-Split Type Indoor Unit Standard'],
        ['PANASONIC', 'CS-QU9YKQ-CU-QU9YKQ', '1.0HP PANASONIC WALL MOUNTED - STANDARD INVERTER (CS-QU9YKQ / CU-QU9YKQ)', '1.0HP', 'WALL MOUNTED', 'CS-QU9YKQ', 'CU-QU9YKQ', 'Standard Inverter'],
        ['PANASONIC', 'CS-QU12YKQ-CU-QU12YKQ', '1.5HP PANASONIC WALL MOUNTED - STANDARD INVERTER (CS-QU12YKQ / CU-QU12YKQ)', '1.5HP', 'WALL MOUNTED', 'CS-QU12YKQ', 'CU-QU12YKQ', 'Standard Inverter'],
        ['PANASONIC', 'CS-QU18YKQ-CU-QU18YKQ', '2.0HP PANASONIC WALL MOUNTED - STANDARD INVERTER (CS-QU18YKQ / CU-QU18YKQ)', '2.0HP', 'WALL MOUNTED', 'CS-QU18YKQ', 'CU-QU18YKQ', 'Standard Inverter'],
        ['PANASONIC', 'CS-QU24YKQ-CU-QU24YKQ', '2.5HP PANASONIC WALL MOUNTED - STANDARD INVERTER (CS-QU24YKQ / CU-QU24YKQ)', '2.5HP', 'WALL MOUNTED', 'CS-QU24YKQ', 'CU-QU24YKQ', 'Standard Inverter'],
        ['PANASONIC', 'CS-QU30YKQ-CU-QU30YKQ', '3.0HP PANASONIC WALL MOUNTED - STANDARD INVERTER (CS-QU30YKQ / CU-QU30YKQ)', '3.0HP', 'WALL MOUNTED', 'CS-QU30YKQ', 'CU-QU30YKQ', 'Standard Inverter'],
        ['PANASONIC', 'CS-RU9AKQ-CU-RU9AKQ', '1.0HP PANASONIC WALL MOUNTED - DELUXE INVERTER (CS-RU9AKQ / CU-RU9AKQ)', '1.0HP', 'WALL MOUNTED', 'CS-RU9AKQ', 'CU-RU9AKQ', 'Deluxe Inverter'],
        ['PANASONIC', 'CS-RU12AKQ-CU-RU12AKQ', '1.5HP PANASONIC WALL MOUNTED - DELUXE INVERTER (CS-RU12AKQ / CU-RU12AKQ)', '1.5HP', 'WALL MOUNTED', 'CS-RU12AKQ', 'CU-RU12AKQ', 'Deluxe Inverter'],
        ['PANASONIC', 'CS-RU18AKQ-CU-RU18AKQ', '2.0HP PANASONIC WALL MOUNTED - DELUXE INVERTER (CS-RU18AKQ / CU-RU18AKQ)', '2.0HP', 'WALL MOUNTED', 'CS-RU18AKQ', 'CU-RU18AKQ', 'Deluxe Inverter'],
        ['PANASONIC', 'CS-RU24AKQ-CU-RU24AKQ', '2.5HP PANASONIC WALL MOUNTED - DELUXE INVERTER (CS-RU24AKQ / CU-RU24AKQ)', '2.5HP', 'WALL MOUNTED', 'CS-RU24AKQ', 'CU-RU24AKQ', 'Deluxe Inverter'],
        ['PANASONIC', 'CS-RU30AKQ-CU-RU30AKQ', '3.0HP PANASONIC WALL MOUNTED - DELUXE INVERTER (CS-RU30AKQ / CU-RU30AKQ)', '3.0HP', 'WALL MOUNTED', 'CS-RU30AKQ', 'CU-RU30AKQ', 'Deluxe Inverter'],
        ['PANASONIC', 'CS-QU9AKQ-CU-QU9AKQ', '1.0HP PANASONIC WALL MOUNTED - STANDARD INVERTER (CS-QU9AKQ / CU-QU9AKQ)', '1.0HP', 'WALL MOUNTED', 'CS-QU9AKQ', 'CU-QU9AKQ', 'Standard Inverter'],
        ['PANASONIC', 'CS-QU12AKQ-CU-QU12AKQ', '1.5HP PANASONIC WALL MOUNTED - STANDARD INVERTER (CS-QU12AKQ / CU-QU12AKQ)', '1.5HP', 'WALL MOUNTED', 'CS-QU12AKQ', 'CU-QU12AKQ', 'Standard Inverter'],
        ['PANASONIC', 'CS-QU12AKQ(S)-CU-RU12AKQ(S)', '1.5HP PANASONIC WALL MOUNTED - STANDARD INVERTER (CS-QU12AKQ(S) / CU-RU12AKQ(S))', '1.5HP', 'WALL MOUNTED', 'CS-QU12AKQ(S)', 'CU-RU12AKQ(S)', 'Standard Inverter'],
        ['PANASONIC', 'CS-QU18AKQ-CU-QU18AKQ', '2.0HP PANASONIC WALL MOUNTED - STANDARD INVERTER (CS-QU18AKQ / CU-QU18AKQ)', '2.0HP', 'WALL MOUNTED', 'CS-QU18AKQ', 'CU-QU18AKQ', 'Standard Inverter'],
        ['PANASONIC', 'CS-QU18AKQ(S)-CU-RU18AKQ(S)', '2.0HP PANASONIC WALL MOUNTED - STANDARD INVERTER (CS-QU18AKQ(S) / CU-RU18AKQ(S))', '2.0HP', 'WALL MOUNTED', 'CS-QU18AKQ(S)', 'CU-RU18AKQ(S)', 'Standard Inverter'],
        ['PANASONIC', 'CS-QU24AKQ-CU-QU24AKQ', '2.5HP PANASONIC WALL MOUNTED - STANDARD INVERTER (CS-QU24AKQ / CU-QU24AKQ)', '2.5HP', 'WALL MOUNTED', 'CS-QU24AKQ', 'CU-QU24AKQ', 'Standard Inverter'],
        ['PANASONIC', 'CS-QU24AKQ(S)-CU-RU24AKQ(S)', '2.5HP PANASONIC WALL MOUNTED - STANDARD INVERTER (CS-QU24AKQ(S) / CU-RU24AKQ(S))', '2.5HP', 'WALL MOUNTED', 'CS-QU24AKQ(S)', 'CU-RU24AKQ(S)', 'Standard Inverter'],
        ['PANASONIC', 'S-34PU3Q-U-34PR1Q6', '4.0HP PANASONIC CEILING CASSETTE INVERTER - 4 WAY (S-34PU3Q / U-34PR1Q6)', '4.0HP', 'CEILING CASSETTE', 'S-34PU3Q', 'U-34PR1Q6', '4 WAY'],
        ['PANASONIC', 'S-28MK2E5A-', '1.0HP PANASONIC WALL MOUNTED - PANASONIC WALL MOUNTED INV (S-28MK2E5A)', '1.0HP', 'WALL MOUNTED', 'S-28MK2E5A', '', 'Panasonic Wall Mounted Inv'],
        ['PANASONIC', 'S-45MK2E5A-', '1.5HP PANASONIC WALL MOUNTED - PANASONIC WALL MOUNTED INV (S-45MK2E5A)', '1.5HP', 'WALL MOUNTED', 'S-45MK2E5A', '', 'Panasonic Wall Mounted Inv'],
        ['PANASONIC', 'S-56MK2E5A-', '2.0HP PANASONIC WALL MOUNTED - PANASONIC WALL MOUNTED INV (S-56MK2E5A)', '2.0HP', 'WALL MOUNTED', 'S-56MK2E5A', '', 'Panasonic Wall Mounted Inv'],
        ['PANASONIC', 'U-6LE2H4-', '6.0HP PANASONIC WALL MOUNTED - PANASONIC MULTI V (U-6LE2H4)', '6.0HP', 'WALL MOUNTED', '', 'U-6LE2H4', 'Panasonic Multi V'],
        ['PANASONIC', 'U-5LE2H4-', '5.0HP PANASONIC WALL MOUNTED - PANASONIC MULTI V (U-5LE2H4)', '5.0HP', 'WALL MOUNTED', '', 'U-5LE2H4', 'Panasonic Multi V'],
        ['PANASONIC', 'CS-PS24SKQ-CU-PS24SKQ', '2.5HP PANASONIC WALL MOUNTED - PANASONIC STANDARD INVERTER (CS-PS24SKQ / CU-PS24SKQ)', '2.5HP', 'WALL MOUNTED', 'CS-PS24SKQ', 'CU-PS24SKQ', 'Panasonic Standard Inverter'],
        ['PANASONIC', 'U-34PR1Q6-', '4.0HP PANASONIC CEILING MOUNTED - PANASONIC CEILING MOUNTED SPLIT TYPE INVERTER (U-34PR1Q6)', '4.0HP', 'CEILING MOUNTED', '', 'U-34PR1Q6', 'Panasonic Ceiling Mounted Split Type Inverter'],
        ['PANASONIC', 'U-43PR1Q6-', '5.0HP PANASONIC CEILING MOUNTED - PANASONIC CEILING MOUNTED SPLIT TYPE INVERTER (U-43PR1Q6)', '5.0HP', 'CEILING MOUNTED', '', 'U-43PR1Q6', 'Panasonic Ceiling Mounted Split Type Inverter'],
        ['PANASONIC', 'CU-2U18YBZ-', '2.0HP PANASONIC MULTI-SPLIT - PANASONIC MULTI OUTDOOR UNIT INVERTER (CU-2U18YBZ)', '2.0HP', 'MULTI-SPLIT', '', 'CU-2U18YBZ', 'Panasonic Multi Outdoor Unit Inverter'],
        ['PANASONIC', 'CU-4U28YBZ-', '3.5HP PANASONIC MULTI-SPLIT - PANASONIC MULTI SPLIT ODU UNIT INVERTER (CU-4U28YBZ)', '3.5HP', 'MULTI-SPLIT', '', 'CU-4U28YBZ', 'Panasonic Multi Split Odu Unit Inverter'],
        ['PANASONIC', 'CS-MXPU12YKZ-', '1.5HP PANASONIC MULTI-SPLIT - PANASONIC MULTI SPLIT INDO UNIT INVERTER (CS-MXPU12YKZ)', '1.5HP', 'MULTI-SPLIT', 'CS-MXPU12YKZ', '', 'Panasonic Multi Split Indo Unit Inverter'],
        ['PANASONIC', 'CX-MPXPU09YKX-', '1.0HP PANASONIC WALL MOUNTED - PANASONIC MULTI SPLIT INDO UNIT INVERTER (CX-MPXPU09YKX)', '1.0HP', 'WALL MOUNTED', 'CX-MPXPU09YKX', '', 'Panasonic Multi Split Indo Unit Inverter'],
        ['PANASONIC', 'CX-MPXPU18YKX-', '2.0HP PANASONIC WALL MOUNTED - PANASONIC MULTI SPLIT INDO UNIT INVERTER (CX-MPXPU18YKX)', '2.0HP', 'WALL MOUNTED', 'CX-MPXPU18YKX', '', 'Panasonic Multi Split Indo Unit Inverter'],
        ['PANASONIC', 'CS-MXPU18YKZ-', '2.0HP PANASONIC MULTI-SPLIT - PANASONIC MULTI SPLIT INDO UNIT INVERTER (CS-MXPU18YKZ)', '2.0HP', 'MULTI-SPLIT', 'CS-MXPU18YKZ', '', 'Panasonic Multi Split Indo Unit Inverter'],
        ['PANASONIC', 'ZF-56XPGECH5VP-', '0HP PANASONIC CEILING FAN - (AC) - DARK GREY 292 (ZF-56XPGECH5VP)', '0HP', 'CEILING FAN', 'ZF-56XPGECH5VP', '', '(AC) - Dark Grey 292'],
    ];

    // Check for existing products and update or insert
    $insertSql = "INSERT INTO products (brand, model, unit_description, horsepower, unit_type, indoor_model, outdoor_model, series, has_outdoor_unit, created_at) 
                  VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, NOW())
                  ON DUPLICATE KEY UPDATE
                  unit_description = VALUES(unit_description),
                  horsepower = VALUES(horsepower),
                  unit_type = VALUES(unit_type),
                  indoor_model = VALUES(indoor_model),
                  outdoor_model = VALUES(outdoor_model),
                  series = VALUES(series),
                  has_outdoor_unit = VALUES(has_outdoor_unit)
                
    ";

    $stmt = $pdo->prepare($insertSql);

    // Begin transaction
    $pdo->beginTransaction();

    $successCount = 0;
    $updateCount = 0;
    $errorCount = 0;
    $errors = [];

    // Process each product
    foreach ($newProducts as $index => $product) {
        try {
            // Determine if it has outdoor unit
            $hasOutdoorUnit = !empty($product[6]) ? 1 : 0;
            
            // Check if product already exists
            $checkStmt = $pdo->prepare("SELECT id FROM products WHERE model = ?");
            $checkStmt->execute([$product[1]]);
            $exists = $checkStmt->fetch();
            
            $stmt->execute([
                $product[0], // brand
                $product[1], // model
                $product[2], // unit_description
                $product[3], // horsepower
                $product[4], // unit_type
                $product[5], // indoor_model
                $product[6], // outdoor_model
                $product[7], // series
                $hasOutdoorUnit // has_outdoor_unit
            ]);
            
            if ($exists) {
                $updateCount++;
            } else {
                $successCount++;
            }
        } catch (PDOException $e) {
            $errorCount++;
            $errors[] = "Row " . ($index + 1) . " (Model: " . $product[1] . "): " . $e->getMessage();
        }
    }

    // Commit transaction
    if ($errorCount === 0) {
        $pdo->commit();
        echo "<h2>✅ Success!</h2>";
        echo "<p><strong>New products added:</strong> $successCount</p>";
        echo "<p><strong>Existing products updated:</strong> $updateCount</p>";
        echo "<p><strong>Total processed:</strong> " . ($successCount + $updateCount) . "</p>";
    } else {
        $pdo->rollback();
        echo "<h2>❌ Errors Occurred</h2>";
        echo "<p>$successCount new products added, $updateCount updated, $errorCount failed.</p>";
        echo "<h3>Error Details:</h3>";
        foreach ($errors as $error) {
            echo "<p style='color: red;'>$error</p>";
        }
    }

} catch (PDOException $e) {
    echo "<h2>❌ Database Connection Error</h2>";
    echo "<p style='color: red;'>Connection failed: " . $e->getMessage() . "</p>";
}

// Display summary
if (($successCount + $updateCount) > 0) {
    echo "<h3>📋 PANASONIC Products Processed:</h3>";
    echo "<table border='1' style='border-collapse: collapse; width: 100%; font-size: 12px;'>";
    echo "<tr style='background-color: #f2f2f2;'>
            <th>Brand</th>
            <th>Model</th>
            <th>Unit Description</th>
            <th>Horsepower</th>
            <th>Type</th>
            <th>Indoor Model</th>
            <th>Outdoor Model</th>
            <th>Series</th>
          </tr>";
    
    foreach ($newProducts as $product) {
        echo "<tr>";
        echo "<td>" . htmlspecialchars($product[0]) . "</td>";
        echo "<td>" . htmlspecialchars($product[1]) . "</td>";
        echo "<td>" . htmlspecialchars($product[2]) . "</td>";
        echo "<td>" . htmlspecialchars($product[3]) . "</td>";
        echo "<td>" . htmlspecialchars($product[4]) . "</td>";
        echo "<td>" . htmlspecialchars($product[5]) . "</td>";
        echo "<td>" . htmlspecialchars($product[6]) . "</td>";
        echo "<td>" . htmlspecialchars($product[7]) . "</td>";
        echo "</tr>";
    }
    echo "</table>";
}

echo "<br><a href='../sales_order_form.html'>← Back to Sales Order Form</a>";
?>